### ISSUE TITLE
Logo needed

### ISSUE THREAD

**Issue by nicola** [multiformats/multiformats#1]
A logo for the repository, future stickers & so on

**Comment by RichardLitt** [comment]
@dignifiedquire Do you want to help on this?

**Comment by dignifiedquire** [comment]
I can schedule this in for the agency. Need to know if there are specific deadlines to be met.

**Comment by RichardLitt** [comment]
As soon as possible would be good. Recent request [here](https://github.com/Fil/php-multihash/issues/1#issuecomment-237915713).

**Comment by jbenet** [comment]
Between now and the final logo, let's get a reasonable placeholder. a hex or something, with "m" or "mfmt" or something.

**Comment by dignifiedquire** [comment]
Okay, will get something temporary for github together next week

**Comment by RichardLitt** [comment]
Interim logo uploaded.

**Comment by dignifiedquire** [comment]
Thanks @RichardLitt I am happy to have that until we get one made :)

**Comment by diasdavid** [comment]
Here is my adaptation
![image](https://cloud.githubusercontent.com/assets/1211152/17703246/ea153304-63c8-11e6-8984-e6483b8646c3.png)

**Comment by RichardLitt** [comment]
AHahahahhaa. I love it, but I think we should keep it like it is, for now.

**Comment by jbenet** [comment]
wolololol

**Comment by RichardLitt** [comment]
![](https://i.ytimg.com/vi/3tBqdKGiqnI/hqdefault.jpg)

**Comment by daviddias** [comment]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/1211152/48905954-e1f1fd00-ee5a-11e8-93ba-fe056cc689cf.png">

:0
