### ISSUE TITLE
Standardize all multiformat READMEs

### ISSUE THREAD

**Issue by RichardLitt** [multiformats/multiformats#13]
Apply [standard-readme](https://github.com/RichardLitt/standard-readme) to all of these repositories:
- [x] [c-multihash](https://github.com/multiformats/c-multihash)
- [x] [clj-multicodec](https://github.com/multiformats/clj-multicodec)
- [x] [clj-multihash](https://github.com/multiformats/clj-multihash)
- [x] [ex_multihash](https://github.com/multiformats/ex_multihash)
- [x] [go-multiaddr](https://github.com/multiformats/go-multiaddr)
- [x] [go-multiaddr-net](https://github.com/multiformats/go-multiaddr-net)
- [x] [go-multicodec](https://github.com/multiformats/go-multicodec)
- [x] [go-multigram](https://github.com/multiformats/go-multigram)
- [x] [go-multihash](https://github.com/multiformats/go-multihash)
- [x] [go-multistream](https://github.com/multiformats/go-multistream)
- [x] [haskell-multihash](https://github.com/multiformats/haskell-multihash)
- [x] [js-multiaddr](https://github.com/multiformats/js-multiaddr)
- [x] [js-multihash](https://github.com/multiformats/js-multihash)
- [x] [js-multihashing](https://github.com/multiformats/js-multihashing)
- [x] [js-multistream](https://github.com/multiformats/js-multistream)
- [x] [multiaddr](https://github.com/multiformats/multiaddr)
- [x] [multicodec](https://github.com/multiformats/multicodec)
- [x] [multiformats](https://github.com/multiformats/multiformats)
- [x] [multihash](https://github.com/multiformats/multihash)
- [x] [MultiHash.Net (fork)](https://github.com/multiformats/MultiHash.Net)
- [x] [multistream](https://github.com/multiformats/multistream)
- [x] [php-multihash](https://github.com/multiformats/php-multihash)
- [x] [rust-multiaddr](https://github.com/multiformats/rust-multiaddr)
- [x] [rust-multihash](https://github.com/multiformats/rust-multihash)
- [x] [scala-multihash](https://github.com/multiformats/scala-multihash)
- [x] [specs](https://github.com/multiformats/specs)
- [x] [SwiftMultiaddr](https://github.com/multiformats/SwiftMultiaddr)
- [x] [SwiftMultihash](https://github.com/multiformats/SwiftMultihash)
- [x] [unsigned-varint](https://github.com/multiformats/unsigned-varint)

**Comment by RichardLitt** [comment]
Wheh. Done. Sorry about that. Comments welcome.

**Comment by lgierth** [comment]
I love the standardized readmes -- not just for the consistency, but also for he boilerplate. It's really nice to dive into writing the readme right away without having to take care of a skeleton with ribbons, licensing, contributing, etc. -- maybe this could be a proper tool? Something like `git clone therepo && init-protocol-repo`?

**Comment by RichardLitt** [comment]
There is a [generator](https://github.com/RichardLitt/generator-standard-readme) you can use for this! Or did you have something else in mind?

**Comment by lgierth** [comment]
Yes excellent, thanks :)
