### ISSUE TITLE
Which repo for spec documents

### ISSUE THREAD

**Issue by lgierth** [multiformats/multiformats#14]
(This might have been covered somewhere and slipped through my backlog speedrun.)

There's the specs repo, but I actually find it nicer to have the spec documents in the respective project repos (e.g. multigram or multihash), and use specs.git mainly for things that don't have their own repo yet. Maybe it can even be merged into multiformats.git.

We could just as well decide this on a per-project basis.

**Comment by jbenet** [comment]
Yeah I think I'm +1 to specs in per project too. I found myself thinking it
too.

**Comment by RichardLitt** [comment]
Agreed with per-project basis. I think merging specs into multiformats make sense. Shall I go ahead and do that?
