### ISSUE TITLE
Move clj-varint to multiformats organization?

### ISSUE THREAD

**Issue by ekroon** [multiformats/multiformats#17]
We have created a clj-varint [1] library as we needed "real" varint support for clj-multihash [2]. As clj-multihash is moved to the multiformats organization, would it be useful to move clj-varint to multiformats also? 

We are going to create a PR to use clj-varint as a dependency in clj-multihash separately. 

[1] https://github.com/mpare-net/clj-varint
[2] https://github.com/multiformats/clj-multihash

**Comment by RichardLitt** [comment]
This sounds good to me. @jbenet?

**Comment by jbenet** [comment]
SGTM

**Comment by RichardLitt** [comment]
@ekroon I have invited you to the organization. You should be able to move it to multiformats, now; after you have done so, I will re-add you as an admin of the repository, and PR your repo for Readme standardization and add links to it from the README in this repo. Sound good?

**Comment by ekroon** [comment]
@RichardLitt sounds great :)

**Comment by ekroon** [comment]
@RichardLitt the repo is moved

**Comment by RichardLitt** [comment]
Awesome. Thanks!
