### ISSUE TITLE
More C# implementations

### ISSUE THREAD

**Issue by tabrath** [multiformats/multiformats#35]
Hi, I've created two more implementations in C#.

* [cs-multibase](https://github.com/tabrath/cs-multibase)
* [cs-multiaddress](https://github.com/tabrath/cs-multiaddress)

Would you be interested in me moving those repositories to the organization?

**Comment by RichardLitt** [comment]
Yup! Move 'em over.

**Comment by tabrath** [comment]
Ok, nice. Will do it soon 👍

**Comment by tabrath** [comment]
Done, and I also transferred cs-multicodec.

**Comment by RichardLitt** [comment]
Sounds good! At some point I'll go through and give your README a comb-over.
