### ISSUE TITLE
Transferring all multiformats to this organization

### ISSUE THREAD

**Issue by RichardLitt** [multiformats/multiformats#4]
### What

We need to move all multiformats to this organization. 

**This list can be edited. Please check off or mark as irrelevant any repositories. **

### List

There are a wide variety of multiformats. These are the main ones:

- [x] multiaddr
- [x] mulithash
- [ ] multikey
- [x] multicodec
- [x] multistream
- [ ] multibase

I am not sure that these exist, but I found them referenced in various places:

- [ ] multispecs
- [ ] multi-multiplexing (multimux?) - See https://github.com/ipfs/specs/issues/33
- [ ] multitransport
- [ ] multiplex - See https://github.com/ipfs/ipfs/blob/252d3f2a05995adb944707951f26ebed08ce1a32/ROADMAP.md#multi-protocols
- [ ] multiproc - See https://github.com/ipfs/ipfs/blob/252d3f2a05995adb944707951f26ebed08ce1a32/ROADMAP.md#multi-protocols
- [ ] multicast - https://github.com/ipfs/ipfs/blob/252d3f2a05995adb944707951f26ebed08ce1a32/ROADMAP.md#multi-protocols
- [ ] multihop - https://github.com/ipfs/ipfs/blob/252d3f2a05995adb944707951f26ebed08ce1a32/ROADMAP.md#multi-protocols
- [ ] multipart - https://github.com/ipfs/ipfs/blob/252d3f2a05995adb944707951f26ebed08ce1a32/ROADMAP.md#multi-protocols

I would also like to have all of the implementations in here: 

- [x]  multiaddr: protocol design
  - [x]  multiaddr: impl in Go
  - [x]  multiaddr: impl in JS
  - [ ]  multiaddr: impl in Java
  - [ ]  multiaddr: impl in Haskell
  - [ ]  multiaddr: impl in Python
  - [ ]  multiaddr: impl in Rust
- [x]  multihash: protocol spec
  - [x]  multihash: impl in Go
  - [x]  multihash: impl in JS
  - [ ]  multihash: impl in Scala
  - [ ]  multihash: impl in Java
  - [ ]  multihash: impl in Clojure
  - [ ]  multihash: impl in Rust
  - [ ]  multihash: impl in Haskell
  - [ ]  multihash: impl in Python
  - [ ]  multihash: impl in Elixir
  - [ ]  multihash: impl in Swift
  - [ ]  multihash: impl in Ruby
- [x]  multicodec: protocol spec
  - [x]  multicodec: impl in Go
  - [ ]  multicodec: impl in JS
- [x]  multistream: protocol spec
  - [ ]  multistream: impl in Go
  - [ ]  multistream: impl in JS
- [ ] multibase / baseN: protocol spec _May not exist?_
  - [ ] multibase / baseN: impl in Go
  - [ ] multibase / baseN: impl in JS

One's that @jbenet needs to move over, from [his list of repos](https://github.com/search?q=user%3Ajbenet+multi&type=Repositories&utf8=%E2%9C%93):

- [x] https://github.com/jbenet/go-multiaddr
- [x] https://github.com/jbenet/js-multihash
- [x] https://github.com/jbenet/go-multihash
- [x] https://github.com/jbenet/js-multiaddr
- [x] https://github.com/jbenet/js-multihashing (_What is this?_)
- [x] https://github.com/jbenet/go-multiaddr-net (_What is this?_)
- [x] https://github.com/jbenet/go-multicodec
- [ ] https://github.com/jbenet/go-peerstream

And diasdavid: diasdavid/js-multistream, diasdavid/multistream-netcat, diasdavid/node-multiplex-stream-muxer, diasdavid/js-multistream-netcat.

**Comment by jbenet** [comment]
go-peerstream is a libp2p thing if anything

**Comment by jbenet** [comment]
thanks @RichardLitt ! moved mine

**Comment by RichardLitt** [comment]
@jbenet Should we not move over all of the implementations, then? We could ask people to move them to this organization.

**Comment by jbenet** [comment]
Yeah I'd be in favor of moving to this org. It's very much a request
though, their choice

**Comment by RichardLitt** [comment]
Can I have approval that none of these exist as specs anywhere, or written in some repo?

- [ ] multispecs
- [ ] multi-multiplexing (multimux?) - See https://github.com/ipfs/specs/issues/33
- [ ] multitransport
- [ ] multiplex - See [this roadmap file](https://github.com/ipfs/ipfs/blob/252d3f2a05995adb944707951f26ebed08ce1a32/ROADMAP.md#multi-protocols)
- [ ] multiproc - See [this roadmap file](https://github.com/ipfs/ipfs/blob/252d3f2a05995adb944707951f26ebed08ce1a32/ROADMAP.md#multi-protocols)
- [ ] multicast - See [this roadmap file](https://github.com/ipfs/ipfs/blob/252d3f2a05995adb944707951f26ebed08ce1a32/ROADMAP.md#multi-protocols)
- [ ] multihop - See [this roadmap file](https://github.com/ipfs/ipfs/blob/252d3f2a05995adb944707951f26ebed08ce1a32/ROADMAP.md#multi-protocols)
- [ ] multipart - See [this roadmap file](https://github.com/ipfs/ipfs/blob/252d3f2a05995adb944707951f26ebed08ce1a32/ROADMAP.md#multi-protocols)

**Comment by RichardLitt** [comment]
Pinged all of the authors - thanks, all. I'm going to consider this closed when we have responses from them.

**Comment by diasdavid** [comment]
> multicast - See this roadmap file
 multihop - See this roadmap file
 multipart - See this roadmap file

These are not multiformats

> multi-multiplexing (multimux?) - See ipfs/specs#33

Not a thing

>  multiplex - See this roadmap file

Also not a multiformat

**Comment by RichardLitt** [comment]
What about -proc and -transport?

**Comment by diasdavid** [comment]
I don't think those are things either

**Comment by RichardLitt** [comment]
Well that settles that then. And, on second thought, since none of the other implementations mandatorily need to move here in any timeframe, I am going to close this issue. Discussion can continue; reopen as needed.
