### ISSUE TITLE
fn code on image multihash.005.jpg is obsolete

### ISSUE THREAD

**Issue by zyyw** [multiformats/multiformats#48]
According to https://github.com/multiformats/multicodec/blob/master/table.csv, the code for sha2-256 is 0x12, while it's 11 in the image, https://github.com/multiformats/multiformats/blob/master/img/multihash.005.jpg

**Comment by Stebalien** [comment]
Hm. That image is _very_ outdated. I'll see if we can find the source and recreate it.

**Comment by jbenet** [comment]
Here's what i've got https://ipfs.io/ipfs/QmNuDVHRbUH9SrPiFy3ZtoiDdtAPGPenpoYMpiz9UDQbaa

sorry, it's keynote. may want to remake it

**Comment by Stebalien** [comment]
For context:

* The document that's out of date is https://github.com/multiformats/multihash#visual-examples. Specifically:
  * https://github.com/multiformats/multihash#idea-self-describe-the-values-to-distinguish
  * https://github.com/multiformats/multihash#multihash-fn-code--length-prefix
* The images are still stored in _this_ repo under `img` (and should probably be moved).
* The codes should:
  * sha2 256: 0x11 -> 0x12
  * sha2 512: 0x12 -> 0x13
  * sha3: 0x14 -> 0x16
  * blake2b: 0x40 -> 0xa0e402

**Comment by jimpick** [comment]
I uploaded the modified keynote file here:

https://gateway.ipfs.io/ipfs/QmWXKt6GqK3nWsLiBPrVatnhKCZNp2zGcfn4sBEkTsLwoU/2019-07-25-multiformats-slides.key
