### ISSUE TITLE
Captains for multiformat repositories

### ISSUE THREAD

**Issue by RichardLitt** [multiformats/multiformats#6]
#### What

I would like to assign captains to each of the Multiformat repositories; their responsibilities would be making sure that issues and pull requests are attended to in a timely manner, and general upkeep. The captains would be listed in a table in the README in this repo. 
#### Why

There are a lot of multiformats, and not everyone has time to focus on them. A few repositories have had issues and pull requests open for a while. It would be great if we could make it a habit in this organization to make sure that repos stay up-to-date and that nothing languishes due to lack of use. 

Here are the repositories currently in the organization: 

| Repo | Suggested Captain |
| --- | --- |
| [c-multihash](https://github.com/multiformats/c-multihash) | @Kubuxu |
| [ex_multihash](https://github.com/multiformats/ex_multihash) | @zabirauf |
| [go-multiaddr](https://github.com/multiformats/go-multiaddr) | @whyrusleeping |
| [go-multiaddr-net](https://github.com/multiformats/go-multiaddr-net) | @whyrusleeping |
| [go-multicodec](https://github.com/multiformats/go-multicodec) | @jbenet |
| [go-multigram](https://github.com/multiformats/go-multigram) | @lgierth |
| [go-multihash](https://github.com/multiformats/go-multihash) | @Kubuxu |
| [go-multistream](https://github.com/multiformats/go-multistream) | @whyrusleeping |
| [js-multiaddr](https://github.com/multiformats/js-multiaddr) | @diasdavid |
| [js-multihash](https://github.com/multiformats/js-multihash) | @diasdavid |
| [js-multihashing](https://github.com/multiformats/js-multihashing) | @diasdavid |
| [js-multistream](https://github.com/multiformats/js-multistream) | @diasdavid |
| [multiaddr](https://github.com/multiformats/multiaddr) | @jbenet |
| [multicodec](https://github.com/multiformats/multicodec) | @jbenet |
| [multiformats](https://github.com/multiformats/multiformats) | @jbenet |
| [multihash](https://github.com/multiformats/multihash) | @jbenet |
| [MultiHash.Net (fork)](https://github.com/multiformats/MultiHash.Net) | @MCGPPeters |
| [multistream](https://github.com/multiformats/multistream) | @diasdavid |
| [php-multihash](https://github.com/multiformats/php-multihash) | @Fil |
| [rust-multiaddr](https://github.com/multiformats/rust-multiaddr) | @dignifiedquire |
| [rust-multihash](https://github.com/multiformats/rust-multihash) | @dignifiedquire |
| [scala-multihash](https://github.com/multiformats/scala-multihash) | @parkan |
| [specs](https://github.com/multiformats/specs) | @nicola |
| [SwiftMultiaddr](https://github.com/multiformats/SwiftMultiaddr) | @NeoTeo |
| [SwiftMultihash](https://github.com/multiformats/SwiftMultihash) | @NeoTeo |
| [unsigned-varint](https://github.com/multiformats/unsigned-varint) | @jbenet |

I would like to add a table with these into the README for this repository, with the names of the people to get in touch with to check in on issues and so on. This will help people know who to contact, and it will allow for better understand of who owns what, as multiformats ages. 

Captaining is a **voluntary** position. All I ask is that, if you don't want to do it anymore, you let me or someone know in an issue, and we can find someone else to take over ownership of the repo. What is important here is that the code is maintained and that we have a plan going forward. 

OSS is hard! What's important is making sure that expectations are met, that people know what they're accountable for, and that no one ever feels trapped. Having clear roles, like this, will help be able to manage those responsibilities and requirements easier than a loose arrangement. What I'm trying to avoid is this sentence: "Well this person is in charge, normally, but they burned out a while ago."

Make sense?
#### To Do
- [ ] Look at the list above, and let me know if you're comfortable with the names I have currently down.

**Comment by jbenet** [comment]
I think i would want a "Maintainer" section (in the readme or as a file) in each repo, so one can easily figure out who the maintainer(s) are, (when looking at a repo).

**Comment by zabirauf** [comment]
Sounds good to me!

**Comment by RichardLitt** [comment]
@jbenet We can rename 'Captain' to 'Maintainer'. I can add this to each repository, too, in the README - probably in the Contribute section, or in the Long Description.

**Comment by dignifiedquire** [comment]
I can take over js-multistream (I just rewrote it) and some of the other js-* if @diasdavid wants less reaponsibilities

**Comment by diasdavid** [comment]
We can share :) I think the word here is just to have someone who knows what is going own and that is responsible for merging and releasing. 

Multistream will have more updates soon with the migration to IPLD

**Comment by NeoTeo** [comment]
Count me in.

**Comment by parkan** [comment]
I'll tentatively maintain scala-multihash, with the possibility of passing it over to https://github.com/yusefnapora

**Comment by nicola** [comment]
will need a co-captain for specs

**Comment by jbenet** [comment]
There can be more than one maintainer, but only one captain. Captain is for
direct source of responsibility over making sure decision making happens,
and for the overall quality of the product.

Why one captain? Having two people in charge of something usually means
neither are. It can work but, Many successful org topologies usually have a
clear responsibility graph ending at an unambiguous directly responsible
individual.

**Comment by RichardLitt** [comment]
@dignifiedquire @diasdavid Are you two OK with how I've allocated captainship?

@nicola You don't have to take any of these! I can take specs; I just wanted to make sure you have something, if you like. Would you rather I take specs?

**Comment by diasdavid** [comment]
@RichardLitt yes, let's go with how it is now, thank you :)

**Comment by RichardLitt** [comment]
@whyrusleeping @Kubuxu @Fil Does this work for you?

**Comment by Fil** [comment]
no problem :-)

**Comment by RichardLitt** [comment]
We should probably remove my name from the 'Maintainers' section in this repo, as I am no longer interested in maintaining this repository. @diasdavid looks like you've been helping out, want to take over?

**Comment by diasdavid** [comment]
Happy to :) Thanks for all the help @RichardLitt ❤️
